feat: adding tap endpoints
fireblocks/fireblocks-sdk-py pull request #123
Opened 2023-09-05 14:52 UTC by asafs932

2023-09-07 11:30 UTC, zoharsf approved these changes

2023-09-11 08:17 UTC, YoavBZ requested changes
Instead of using `Any`, please add the new types to `api_types.py` and use them

2023-09-18 16:07 UTC, asafs932 commented
> Instead of using `Any`, please add the new types to `api_types.py` and use them

@YoavBZ please review again

2023-09-22 09:47 UTC, YoavBZ approved these changes

2023-09-22 09:48 UTC, merged