added groups endpoints
fireblocks/fireblocks-sdk-py pull request #124
Opened 2023-09-07 11:25 UTC by nitaiaharoni1

2023-09-07 11:39 UTC, asafs932 approved these changes

2023-09-07 11:39 UTC, asafs932 commented on fireblocks_sdk/sdk.py
> +        @param member_ids: The members of the Users Group
```suggestion
        @param member_ids: The ids of the Users Group members
```

2023-09-07 11:39 UTC, asafs932 commented on fireblocks_sdk/sdk.py
> +        @param member_ids: The members of the Users Group
```suggestion
        @param member_ids: The ids of the Users Group members
```

2023-09-11 08:50 UTC, YoavBZ requested changes
You're missing an import to `Any`

2023-09-12 07:59 UTC, asafs932 approved these changes

2023-09-13 08:56 UTC, YoavBZ approved these changes

2023-09-13 08:57 UTC, merged